services:
  docmost:
    image: docmost/docmost:local
    depends_on:
      - db
      - redis
    environment:
      APP_URL: ${APP_URL:-http://localhost:3000}
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      STORAGE_DRIVER: ${STORAGE_DRIVER:-local}
      DISABLE_TELEMETRY: ${DISABLE_TELEMETRY:-false}
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - docmost:/app/data/storage
      - ./apps/server/dist:/app/apps/server/dist:ro
      - ./apps/client/dist:/app/apps/client/dist:ro
      - ./packages/editor-ext/dist:/app/packages/editor-ext/dist:ro

  db:
    image: postgres:18
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-docmost}
      POSTGRES_USER: ${POSTGRES_USER:-docmost}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql

  redis:
    image: redis:8
    command: ["redis-server", "--appendonly", "yes", "--maxmemory-policy", "noeviction"]
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  docmost:
  db_data:
  redis_data:
